import React, { useState } from 'react'
import {
  ShieldCheck,
  RotateCcw,
  CheckCircle2,
  AlertTriangle,
  Wrench
} from 'lucide-react'
import { Card } from '../components/Card'
import { ProgressBar } from '../components/ProgressBar'
import { initialSecurityChecks } from '../data/mockData'
import type { SecurityCheck } from '../types'

export const SecurityPage: React.FC = () => {
  const [checks, setChecks] = useState<SecurityCheck[]>(initialSecurityChecks)
  const [isScanning, setIsScanning] = useState<boolean>(false)
  const [fixedAlert, setFixedAlert] = useState<boolean>(false)

  const handleRescan = () => {
    setIsScanning(true)
    setTimeout(() => {
      setIsScanning(false)
    }, 1300)
  }

  const handleFixVulnerability = (id: string) => {
    setChecks(
      checks.map((c) =>
        c.id === id
          ? {
              ...c,
              severity: 'Pass',
              status: 'Passed',
              description: 'Dependencies patched. 0 vulnerabilities remaining in AST tree.'
            }
          : c
      )
    )
    setFixedAlert(true)
  }

  return (
    <div className="security-view">
      {/* Header */}
      <div className="sec-header-row">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <h1 className="title-page">Security Audit & AST Analysis</h1>
            <span className="badge badge-completed">SAST Passed</span>
          </div>
          <p className="subtitle">
            Autonomous vulnerability detection and secret sanitization generated by <strong>Security Agent</strong>.
          </p>
        </div>

        <button
          onClick={handleRescan}
          disabled={isScanning}
          className="btn btn-primary btn-sm"
        >
          <RotateCcw className={`w-3.5 h-3.5 ${isScanning ? 'animate-spin' : ''}`} />
          <span>{isScanning ? 'Scanning AST & Dependencies...' : 'Trigger Security Rescan'}</span>
        </button>
      </div>

      {/* Main Banner: Security Score 94/100 */}
      <Card className="score-hero-card" glow="emerald">
        <div className="score-card-layout">
          <div className="score-badge-circle">
            <ShieldCheck className="w-10 h-10 text-emerald-400" />
            <div className="score-num-box">
              <span className="score-value">94</span>
              <span className="score-total">/100</span>
            </div>
          </div>

          <div className="score-text-block">
            <div className="flex items-center gap-3">
              <h2 className="title-section" style={{ fontSize: '20px' }}>Security Posture: Grade A+</h2>
              <span className="badge badge-completed">Enterprise Ready</span>
            </div>
            <p className="text-xs text-slate-300 mt-1 max-w-xl leading-relaxed">
              Automated SAST scanning inspected 1,480 lines of synthesized React and Node.js code.
              Zero high or critical OWASP vulnerabilities detected. 4 out of 5 checks fully verified.
            </p>
            <div className="score-progress-wrapper mt-3">
              <ProgressBar progress={fixedAlert ? 100 : 94} height={6} showPercentage={false} color="emerald" />
            </div>
          </div>

          <div className="score-meta-stats">
            <div className="stat-pill">
              <span className="text-[10px] text-slate-400 uppercase">Critical</span>
              <span className="text-sm font-bold font-mono text-emerald-400">0</span>
            </div>
            <div className="stat-pill">
              <span className="text-[10px] text-slate-400 uppercase">High</span>
              <span className="text-sm font-bold font-mono text-emerald-400">0</span>
            </div>
            <div className="stat-pill">
              <span className="text-[10px] text-slate-400 uppercase">Low</span>
              <span className="text-sm font-bold font-mono text-amber-400">{fixedAlert ? '0' : '1'}</span>
            </div>
          </div>
        </div>
      </Card>

      {/* 5 Core Audit Categories */}
      <div className="audit-categories-section">
        <div className="flex items-center justify-between border-b border-white/10 pb-2 mb-3">
          <h3 className="title-section text-sm font-bold">5 Core Security Checks</h3>
          <span className="text-xs font-mono text-slate-400">OWASP Top 10 Specification</span>
        </div>

        <div className="checks-list">
          {checks.map((check) => {
            const isPass = check.severity === 'Pass'

            return (
              <Card key={check.id} className="security-item-card">
                <div className="check-row-top">
                  <div className="flex items-center gap-3">
                    <div className={`check-icon-circle ${isPass ? 'pass' : 'warn'}`}>
                      {isPass ? (
                        <CheckCircle2 className="w-5 h-5 text-emerald-400" />
                      ) : (
                        <AlertTriangle className="w-5 h-5 text-amber-400" />
                      )}
                    </div>
                    <div>
                      <div className="flex items-center gap-2">
                        <span className="text-xs font-mono text-slate-400 uppercase">
                          [{check.category}]
                        </span>
                        <h4 className="text-sm font-bold text-white">{check.title}</h4>
                      </div>
                      <p className="text-xs text-slate-300 mt-1">{check.description}</p>
                    </div>
                  </div>

                  <div className="check-actions-slot">
                    <span className={`badge ${isPass ? 'badge-completed' : 'badge-warning'}`}>
                      {check.status}
                    </span>
                    {!isPass && check.remediation && (
                      <button
                        onClick={() => handleFixVulnerability(check.id)}
                        className="btn btn-secondary btn-sm text-indigo-300 hover:text-white"
                      >
                        <Wrench className="w-3 h-3" />
                        <span>Auto-Remediate</span>
                      </button>
                    )}
                  </div>
                </div>

                {check.remediation && !isPass && (
                  <div className="remediation-box mt-3">
                    <span className="text-[11px] font-semibold text-amber-300 block mb-0.5">
                      AI Suggested Remediation:
                    </span>
                    <p className="text-xs font-mono text-slate-300">{check.remediation}</p>
                  </div>
                )}
              </Card>
            )
          })}
        </div>
      </div>

      <style>{`
        .security-view {
          display: flex;
          flex-direction: column;
          gap: 24px;
        }
        .sec-header-row {
          display: flex;
          justify-content: space-between;
          align-items: center;
          flex-wrap: wrap;
          gap: 16px;
        }
        .score-hero-card {
          padding: 24px 28px;
        }
        .score-card-layout {
          display: flex;
          align-items: center;
          gap: 28px;
          flex-wrap: wrap;
        }
        .score-badge-circle {
          display: flex;
          align-items: center;
          gap: 14px;
          background: rgba(16, 185, 129, 0.1);
          border: 1px solid rgba(16, 185, 129, 0.3);
          padding: 14px 20px;
          border-radius: 16px;
        }
        .score-num-box {
          display: flex;
          align-items: baseline;
        }
        .score-value {
          font-size: 38px;
          font-weight: 800;
          font-family: var(--font-mono);
          color: #ffffff;
          line-height: 1;
        }
        .score-total {
          font-size: 16px;
          color: #94a3b8;
          font-family: var(--font-mono);
        }
        .score-text-block {
          flex: 1;
          min-width: 280px;
        }
        .score-progress-wrapper {
          max-width: 420px;
        }
        .score-meta-stats {
          display: flex;
          gap: 12px;
        }
        .stat-pill {
          padding: 10px 16px;
          border-radius: 10px;
          background: rgba(255, 255, 255, 0.03);
          border: 1px solid var(--border-subtle);
          display: flex;
          flex-direction: column;
          align-items: center;
          min-width: 65px;
        }
        .audit-categories-section {
          display: flex;
          flex-direction: column;
          gap: 12px;
        }
        .checks-list {
          display: flex;
          flex-direction: column;
          gap: 12px;
        }
        .security-item-card {
          padding: 16px 20px;
        }
        .check-row-top {
          display: flex;
          justify-content: space-between;
          align-items: center;
          flex-wrap: wrap;
          gap: 16px;
        }
        .check-icon-circle {
          width: 36px;
          height: 36px;
          border-radius: 10px;
          display: flex;
          align-items: center;
          justify-content: center;
          flex-shrink: 0;
        }
        .check-icon-circle.pass {
          background: rgba(16, 185, 129, 0.12);
        }
        .check-icon-circle.warn {
          background: rgba(245, 158, 11, 0.12);
        }
        .check-actions-slot {
          display: flex;
          align-items: center;
          gap: 10px;
        }
        .remediation-box {
          background: rgba(245, 158, 11, 0.08);
          border-left: 2px solid #f59e0b;
          border-radius: 0 6px 6px 0;
          padding: 8px 12px;
        }
      `}</style>
    </div>
  )
}
