import React, { useState } from 'react'
import {
  Play,
  Search,
  Clock,
  Check
} from 'lucide-react'
import { Card } from '../components/Card'
import { ProgressBar } from '../components/ProgressBar'
import { initialTestCases } from '../data/mockData'
import type { TestCase } from '../types'

export const TestingPage: React.FC = () => {
  const [testCases, setTestCases] = useState<TestCase[]>(initialTestCases)
  const [filterType, setFilterType] = useState<string>('all')
  const [searchQuery, setSearchQuery] = useState<string>('')
  const [isRunningAll, setIsRunningAll] = useState<boolean>(false)

  const handleRunTests = () => {
    setIsRunningAll(true)
    setTestCases((prev) => prev.map((t) => ({ ...t, status: 'Running' })))

    setTimeout(() => {
      setTestCases((prev) => prev.map((t) => ({ ...t, status: 'Passed' })))
      setIsRunningAll(false)
    }, 1400)
  }

  const filteredTests = testCases.filter((test) => {
    const matchesType = filterType === 'all' || test.type.toLowerCase() === filterType.toLowerCase()
    const matchesSearch =
      test.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
      test.suite.toLowerCase().includes(searchQuery.toLowerCase())
    return matchesType && matchesSearch
  })

  return (
    <div className="testing-view">
      {/* Header */}
      <div className="testing-header-row">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <h1 className="title-page">Automated Quality Assurance & Testing</h1>
            <span className="badge badge-completed">Vitest 3.0 + Playwright E2E</span>
          </div>
          <p className="subtitle">
            Autonomous unit and integration test synthesis generated by <strong>Testing Agent</strong>.
          </p>
        </div>

        <button
          onClick={handleRunTests}
          disabled={isRunningAll}
          className="btn btn-primary btn-sm"
        >
          {isRunningAll ? (
            <>
              <span className="w-3.5 h-3.5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
              <span>Executing Test Runner...</span>
            </>
          ) : (
            <>
              <Play className="w-3.5 h-3.5" />
              <span>Run All Test Suites</span>
            </>
          )}
        </button>
      </div>

      {/* Top Metric Cards: Total Tests | Passed | Failed | Coverage */}
      <div className="grid-4 testing-metrics-grid">
        <Card className="test-metric-card">
          <span className="metric-title">Total Tests</span>
          <h3 className="metric-number">148</h3>
          <span className="text-xs text-slate-400">8 Test suites across 4 layers</span>
        </Card>

        <Card className="test-metric-card">
          <span className="metric-title">Passed</span>
          <h3 className="metric-number text-emerald-400">142</h3>
          <span className="text-xs text-emerald-400 font-semibold">95.9% Pass rate</span>
        </Card>

        <Card className="test-metric-card">
          <span className="metric-title">Failed</span>
          <h3 className="metric-number text-slate-400">0</h3>
          <span className="text-xs text-slate-400">Zero regression breaks</span>
        </Card>

        <Card className="test-metric-card" glow="emerald">
          <span className="metric-title">Code Coverage</span>
          <h3 className="metric-number text-indigo-300">94.2%</h3>
          <ProgressBar progress={94.2} height={5} showPercentage={false} color="emerald" />
        </Card>
      </div>

      {/* Test Results Table with Filter & Search */}
      <Card
        title="Test Execution Matrix"
        subtitle="Granular assertions synthesized by Testing Agent"
        badge={<span className="text-xs font-mono text-slate-400">{filteredTests.length} tests displayed</span>}
      >
        <div className="table-controls-row">
          <div className="search-field-wrapper">
            <Search className="w-3.5 h-3.5 text-slate-400" />
            <input
              type="text"
              placeholder="Search tests by name or suite file..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="table-search-input"
            />
          </div>

          <div className="filter-buttons-group">
            {['all', 'unit', 'integration', 'e2e', 'security'].map((type) => (
              <button
                key={type}
                onClick={() => setFilterType(type)}
                className={`table-filter-btn ${filterType === type ? 'active' : ''}`}
              >
                {type.toUpperCase()}
              </button>
            ))}
          </div>
        </div>

        <div className="table-responsive-wrapper">
          <table className="data-table">
            <thead>
              <tr>
                <th>Test Name</th>
                <th>Type</th>
                <th>Status</th>
                <th>Duration</th>
                <th>Assertions</th>
              </tr>
            </thead>
            <tbody>
              {filteredTests.map((test) => (
                <tr key={test.id}>
                  <td>
                    <div className="flex flex-col">
                      <span className="font-semibold text-white text-xs">{test.name}</span>
                      <span className="font-mono text-[11px] text-slate-400">{test.suite}</span>
                    </div>
                  </td>
                  <td>
                    <span className="text-xs font-mono px-2 py-0.5 rounded bg-white/5 border border-white/10 text-slate-300">
                      {test.type}
                    </span>
                  </td>
                  <td>
                    {test.status === 'Passed' && (
                      <span className="badge badge-completed">
                        <Check className="w-3 h-3" /> Passed
                      </span>
                    )}
                    {test.status === 'Running' && (
                      <span className="badge badge-running">
                        <span className="pulse-dot" /> Running
                      </span>
                    )}
                    {test.status === 'Failed' && (
                      <span className="badge badge-danger">✕ Failed</span>
                    )}
                  </td>
                  <td>
                    <span className="font-mono text-xs text-slate-300 flex items-center gap-1">
                      <Clock className="w-3 h-3 text-slate-400" />
                      {test.duration}
                    </span>
                  </td>
                  <td>
                    <span className="font-mono text-xs text-indigo-300 font-semibold">
                      {test.assertions} checks
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Card>

      <style>{`
        .testing-view {
          display: flex;
          flex-direction: column;
          gap: 24px;
        }
        .testing-header-row {
          display: flex;
          justify-content: space-between;
          align-items: center;
          flex-wrap: wrap;
          gap: 16px;
        }
        .testing-metrics-grid {
          margin-bottom: 4px;
        }
        .test-metric-card {
          padding: 18px 20px;
          display: flex;
          flex-direction: column;
          gap: 4px;
        }
        .metric-title {
          font-size: 11.5px;
          color: var(--text-muted);
          font-weight: 500;
          text-transform: uppercase;
          letter-spacing: 0.05em;
        }
        .metric-number {
          font-size: 26px;
          font-weight: 700;
          color: #ffffff;
          font-family: var(--font-mono);
          letter-spacing: -0.02em;
        }
        .table-controls-row {
          display: flex;
          justify-content: space-between;
          align-items: center;
          gap: 16px;
          margin-bottom: 16px;
          flex-wrap: wrap;
        }
        .search-field-wrapper {
          position: relative;
          display: flex;
          align-items: center;
          flex: 1;
          max-width: 360px;
        }
        .search-field-wrapper svg {
          position: absolute;
          left: 10px;
          pointer-events: none;
        }
        .table-search-input {
          width: 100%;
          background: #080c14;
          border: 1px solid var(--border-subtle);
          border-radius: 8px;
          padding: 7px 12px 7px 32px;
          color: #ffffff;
          font-size: 12.5px;
        }
        .table-search-input:focus {
          border-color: #6366f1;
        }
        .filter-buttons-group {
          display: flex;
          gap: 6px;
        }
        .table-filter-btn {
          padding: 5px 10px;
          border-radius: 6px;
          background: rgba(255, 255, 255, 0.04);
          border: 1px solid var(--border-subtle);
          color: var(--text-muted);
          font-size: 11px;
          font-weight: 600;
          font-family: var(--font-mono);
          transition: all 0.15s;
        }
        .table-filter-btn:hover {
          color: var(--text-primary);
        }
        .table-filter-btn.active {
          background: rgba(99, 102, 241, 0.15);
          color: #a5b4fc;
          border-color: rgba(99, 102, 241, 0.4);
        }
        .table-responsive-wrapper {
          overflow-x: auto;
        }
      `}</style>
    </div>
  )
}
